export type CustomerType =
    | 'INDIVIDUAL'
    | 'BUSINESS';

export type CustomerStatus =
    | 'ACTIVE'
    | 'INACTIVE'
    | 'ARCHIVED';

export type AddressType =
    | 'HOME'
    | 'BUSINESS'
    | 'BILLING'
    | 'SHIPPING'
    | 'OTHER';

export type ActivityType =
    | 'CUSTOMER_CREATED'
    | 'CUSTOMER_UPDATED'
    | 'CUSTOMER_ARCHIVED'
    | 'CUSTOMER_ACTIVATED'
    | 'CUSTOMER_DEACTIVATED'
    | 'ADDRESS_ADDED'
    | 'ADDRESS_UPDATED'
    | 'ADDRESS_DELETED'
    | 'NOTE_ADDED'
    | 'DOCUMENT_UPLOADED'
    | 'DOCUMENT_DELETED';

/* =========================================================
   CUSTOMER
========================================================= */

export interface Customer {
    /**
     * Internal UUID.
     *
     * Used by the application and API for relationships
     * and routes such as /customers/:id.
     *
     * This should not normally be displayed to users.
     */
    id: string;

    /**
     * System-generated sequential customer number.
     *
     * Example:
     * 1 -> CUS-000001
     *
     * This value is generated by the backend/database
     * and must not be editable by users.
     */
    customerNumber: number;

    type: CustomerType;

    firstName: string | null;
    lastName: string | null;
    businessName: string | null;

    email: string;
    phone: string;

    status: CustomerStatus;

    createdAt: string;
    updatedAt: string;
}

/* =========================================================
   CUSTOMER LIST
========================================================= */

export interface CustomerListResponse {
    success: boolean;

    data: Customer[];

    meta: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
}

/* =========================================================
   ADDRESS
========================================================= */

export interface Address {
    id: string;
    customerId: string;

    type: AddressType;

    addressLine1: string;
    addressLine2: string | null;

    city: string;
    state: string | null;
    postalCode: string | null;
    country: string;

    createdAt: string;
    updatedAt: string;
}

/* =========================================================
   CUSTOMER NOTE
========================================================= */

export interface CustomerNote {
    id: string;
    customerId: string;

    note: string;

    createdAt: string;
    updatedAt: string;

    author: {
        id: string;
        name: string;
        email: string;
    };
}

/* =========================================================
   CUSTOMER DOCUMENT
========================================================= */

export interface CustomerDocument {
    id: string;
    customerId: string;

    uploadedById: string;

    fileName: string;
    mimeType: string;
    fileSize: number;

    documentType: string;

    uploadedAt: string;

    uploadedBy: {
        id: string;
        name: string;
        email: string;
    };
}

/* =========================================================
   CUSTOMER ACTIVITY
========================================================= */

export interface CustomerActivity {
    id: string;
    customerId: string;

    action: ActivityType;

    createdAt: string;

    actor: {
        id: string;
        name: string;
        email: string;
    };
}

/* =========================================================
   CUSTOMER PROFILE
========================================================= */

export interface CustomerProfile
    extends Customer {
    addresses: Address[];
    notes: CustomerNote[];
    documents: CustomerDocument[];
    activities: CustomerActivity[];
}

/* =========================================================
   API RESPONSES
========================================================= */

export interface CustomerProfileResponse {
    success: boolean;
    data: CustomerProfile;
}

export interface CustomerActivityResponse {
    success: boolean;
    data: CustomerActivity[];
}

/* =========================================================
   CUSTOMER DISPLAY HELPERS
========================================================= */

/**
 * Converts the database customer number into the
 * customer-facing reference used throughout CustomerFlow.
 *
 * Examples:
 * 1    -> CUS-000001
 * 25   -> CUS-000025
 * 1250 -> CUS-001250
 */
export const formatCustomerId = (
    customerNumber: number,
): string => {
    return `CUS-${String(customerNumber).padStart(
        6,
        '0',
    )}`;
};

/**
 * Returns the appropriate display name depending
 * on whether the record represents an individual
 * or a business.
 */
export const getCustomerDisplayName = (
    customer: Pick<
        Customer,
        | 'type'
        | 'firstName'
        | 'lastName'
        | 'businessName'
    >,
): string => {
    if (customer.type === 'BUSINESS') {
        return (
            customer.businessName?.trim() ||
            'Unnamed business'
        );
    }

    const fullName = [
        customer.firstName,
        customer.lastName,
    ]
        .filter(Boolean)
        .join(' ')
        .trim();

    return fullName || 'Unnamed customer';
};